apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeforge
  namespace: kubeforge
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubeforge
                port:
                  number: 80
